---
#
# This sets up the directory structure for developing a role
#
- hosts: localhost
  vars:
    - rolename: cpatriot-centos-setup

  tasks:
    - name: Creating Ansible roles directory structure
      file: 
        path: roles
        state: directory
        mode: 0755
    - name: Creating Ansible {{ rolename }} role directory 
      file: 
        path: "roles/{{ rolename }}"
        state: directory
        mode: 0755
    - name: Creating Ansible defaults directory 
      file: 
        path: "roles/{{ rolename }}/defaults"
        state: directory
        mode: 0755
    - name: Creating Ansible main.yml for defaults
      file: 
        path: "roles/{{ rolename }}/defaults/main.yml"
        state: touch
        mode: 0755
    - name: Creating Ansible files directory 
      file: 
        path: "roles/{{ rolename }}/files"
        state: directory
        mode: 0755
    - name: Creating Ansible handlers directory 
      file: 
        path: "roles/{{ rolename }}/handlers"
        state: directory
        mode: 0755
    - name: Creating Ansible main.yml for defaults
      file: 
        path: "roles/{{ rolename }}/handlers/main.yml"
        state: touch
        mode: 0755
    - name: Creating Ansible meta directory 
      file: 
        path: "roles/{{ rolename }}/meta"
        state: directory
        mode: 0755
    - name: Creating Ansible main.yml for defaults
      file: 
        path: "roles/{{ rolename }}/meta/main.yml"
        state: touch
        mode: 0755
    - name: Creating Ansible tasks directory 
      file: 
        path: "roles/{{ rolename }}/tasks"
        state: directory
        mode: 0755
    - name: Creating Ansible main.yml for defaults
      file: 
        path: "roles/{{ rolename }}/tasks/main.yml"
        state: touch
        mode: 0755
    - name: Creating Ansible files directory 
      file: 
        path: "roles/{{ rolename }}/templates"
        state: directory
        mode: 0755

